### ISSUE TITLE
Resend verification email command from whmcs

### ISSUE THREAD

**Issue by shabsta** [hexonet/whmcs-ispapi-registrar#144] opened 2020-05-12 09:09 UTC
Please consider adding the ability to resend the registrant verification email to the registrant from within whmcs, either as a button from the domain's menu under registrar commands and or an option available from the client facing section of whmcs.

**Comment by papakai** [comment] 2020-05-12 11:28
@shabsta thanks for getting in touch with us. Very appreciated! I'll follow-up when we have news.

**Comment by papakai** [comment] 2020-05-13 16:07
@shabsta, are talking about https://developers.whmcs.com/domain-registrars/transfer-policy-management/ `Resend Contact Verification Email`?

If yes, this feature is already available since v1.12.0 (we are right now at v3.0.3). Available for download [here](https://github.com/hexonet/whmcs-ispapi-registrar/releases).

Let me know if I misunderstood something. thanks so much!

**Comment by shabsta** [comment] 2020-05-13 16:23
Thanks for your response

Resend Contact Verification Email
That is the function that resends the registrant verification email. How is
this invoked?

**Comment by papakai** [comment] 2020-05-13 16:40
You're welcome.

When you're in client-area, there's a resend button in case our module returns for the domain that for the domain:
a) IRTP is enabled
b) a contact chage is still pending

An example image I found using google (I don't have a case right now):
![image](https://user-images.githubusercontent.com/229425/81840144-da3f8000-9548-11ea-861b-a89674d6e150.png)

I have not found that this possibility exists somewhere in Admin Area.

**Comment by papakai** [comment] 2020-05-13 16:43
... and as mentioned, this is only available when having Option 2 selected in IRTP settings at registrar module level.

**Comment by papakai** [comment] 2020-05-13 16:56
From point of source code, the Resend Contact Verification Email button/possibility should be available in admin area (script clientsdomains.php) and also in the client area (expecting the domain details view) itself.

Let me know if you still need screenshots where to find these buttons, it needs some time to reproduce such a case on my side.

**Comment by shabsta** [comment] 2020-05-13 17:59
Thank you for all the quick responses, greatly appreciated

I think my issue is this :

Option 2 selected in IRTP

I’ll log into whmcs in the next few minutes and play. If this works then we
are almost there :)

**Comment by shabsta** [comment] 2020-05-13 18:41
@papakai 

Just to confirm, to allow us to resend the registrant verification email we would need to change IRTP to the second option as per my screenshot
<img width="476" alt="2020-05-13_20-38-30" src="https://user-images.githubusercontent.com/43058981/81851606-09122200-955a-11ea-8e5b-7b69852cd790.png">

**Comment by papakai** [comment] 2020-05-13 18:45
👍exactly.

**Comment by papakai** [comment] 2020-05-13 18:46
if this still does not help, let me know the domain name for further investigation and analysis.

**Comment by shabsta** [comment] 2020-05-14 07:04
Morning @papakai 

How do I get in touch with you directly so that I can send you examples without posting client related info on here?

**Comment by papakai** [comment] 2020-05-14 11:05
Hi @shabsta 

I suggest to open a support ticket here: https://hexonet.support/en/new-ticket.php
Ask to get the ticket directly assigned to `Kai Schwarz`.

Best
Kai

**Comment by papakai** [comment] 2020-05-14 11:24
Closing this issue therefore. Awaiting your support ticket.

**Closed by papakai** 2020-05-14 11:24 UTC
