### ISSUE TITLE
Possible bug for .CA registration (OT&E only!)

### ISSUE THREAD

**Issue by DomainePlus** [hexonet/whmcs-ispapi-registrar#221] opened 2022-02-16 20:05 UTC
Hi,

First of all i don't know if this is a bug or just something i don't understand.

**Describe the bug**
When WHMCS send a request to register a .CA domain name to your API in OT&E mode, an error is returned.

**To Reproduce**
1. Search for a .CA domain and add it to your cart
2. On the domain configuration page, choose a non-individual (eg. CCO) as the legal type
3. Complete the order
4. As an administrator, you will receive an email with the subject: "WHMCS Automatic Setup Failed"
5. The error message is: Invalid attribute value; INVALID CONTACT [OWNERCONTACT (Required parameter missing; Organization must be entered when CPR Category indicates a non-individual.)]

But the organization/company is in the request as you can see in the following log entry

**WHMCS Module log**

Request:

```
COMMAND = AddDomain
DOMAIN = test-2022-02-16-missing-org.ca
PERIOD = 1
NAMESERVER0 = ns1.hexonet.net
NAMESERVER1 = ns2.hexonet.net
NAMESERVER2 = ns3.hexonet.net
NAMESERVER3 = 
NAMESERVER4 = 
OWNERCONTACT0FIRSTNAME = Test
OWNERCONTACT0LASTNAME = Contact
OWNERCONTACT0ORGANIZATION = Test compagnie Inc.
OWNERCONTACT0STREET = 123 rue Test
OWNERCONTACT0CITY = Testville
OWNERCONTACT0STATE = QC
OWNERCONTACT0ZIP = J3h6c6
OWNERCONTACT0COUNTRY = CA
OWNERCONTACT0PHONE = 5555555555
OWNERCONTACT0EMAIL = dev@domaineplus.com
ADMINCONTACT0FIRSTNAME = Test
ADMINCONTACT0LASTNAME = Contact
ADMINCONTACT0ORGANIZATION = Test compagnie Inc.
ADMINCONTACT0STREET = 123 rue Test
ADMINCONTACT0CITY = Testville
ADMINCONTACT0STATE = QC
ADMINCONTACT0ZIP = J3h6c6
ADMINCONTACT0COUNTRY = CA
ADMINCONTACT0PHONE = 5555555555
ADMINCONTACT0EMAIL = dev@domaineplus.com
TECHCONTACT0FIRSTNAME = Test
TECHCONTACT0LASTNAME = Contact
TECHCONTACT0ORGANIZATION = Test compagnie Inc.
TECHCONTACT0STREET = 123 rue Test
TECHCONTACT0CITY = Testville
TECHCONTACT0STATE = QC
TECHCONTACT0ZIP = J3h6c6
TECHCONTACT0COUNTRY = CA
TECHCONTACT0PHONE = 5555555555
TECHCONTACT0EMAIL = dev@domaineplus.com
BILLINGCONTACT0FIRSTNAME = Test
BILLINGCONTACT0LASTNAME = Contact
BILLINGCONTACT0ORGANIZATION = Test compagnie Inc.
BILLINGCONTACT0STREET = 123 rue Test
BILLINGCONTACT0CITY = Testville
BILLINGCONTACT0STATE = QC
BILLINGCONTACT0ZIP = J3h6c6
BILLINGCONTACT0COUNTRY = CA
BILLINGCONTACT0PHONE = 5555555555
BILLINGCONTACT0EMAIL = dev@domaineplus.com
TRANSFERLOCK = 1
X-CA-LEGALTYPE = CCO
X-CA-LANGUAGE = FR

Response: 

[RESPONSE]
DESCRIPTION=Invalid attribute value; INVALID CONTACT [OWNERCONTACT (Required parameter missing; Organization must be entered when CPR Category indicates a non-individual.)]
QUEUETIME=0
CODE=541
RUNTIME=0.371

QUEUETIME=0
RUNTIME=0.761

EOF
```

**Context:**
 - Device: Desktop
 - OS: Centos 6 on our server and windows 10 on my computer
 - Browser: 98.0.4758.82
 - WHMCS Version: 8.3.2
 - PHP Version: 7.4
 - ISPAPI Registrar Module Version: 7.2.18

Thanks in advance for your help.

P.S. My native language is french so sorry for my bad english.

**Comment by papakai** [comment] 2022-02-17 11:46
Hi there,

I am impressed by this detailed bug report - that's the way to go! WHMCS Resellers usually don't do that.

This is not a bug of our WHMCS integration. I'll reach out to our backend engineers regarding this issue - looks like .CA is broken for an unknown reason in our OT&E.

I'll keep you posted.

Best

Kai

**Comment by papakai** [comment] 2022-02-18 13:27
First feedback: Looks like CIRA's OT&E is behaving differently compared to the Production Environment. We have to reach out to the registry. I'll keep you posted.

**Comment by papakai** [comment] 2022-02-18 14:05
No, I didn't receive another answer. If you replied by mail, looks like this isn't working.

Hmm! That's great feedback. Probably this is just unknown to our tier-2 support, but known to our engineers / product management. Let me bump this up for further analysis. Thanks so much for the hint.

**Comment by DomainePlus** [comment] 2022-02-28 20:34
Thank you Kai,

We are scheduled to launch our new system next week, in theory, it's supposed to work in production since the update for the CIRA system is supposed to be on April 1. Can you please confirm that your system will be updated by than?

The .CA market is VERY important to us.

**Comment by papakai** [comment] 2022-03-01 06:50
Hi!

.CA is also very important for us - we have several .CA resellers on board and we got this timeline forwarded as well.
I've bumped the importance of all this to our product management. If there's some new information available, I'll let you know.

Best
Kai

**Comment by papakai** [comment] 2022-03-01 19:38
Hi,

OT&E review is assigned and will be processed soon so that you guys can test the changes already in OT&E.
I'll let you know when this got rolled out. Live System will of course follow all this.

Best
Kai

**Comment by papakai** [comment] 2022-03-03 07:01
fyi: the deadline for the LIVE system/production environment got postponed by CIRA to April 21st. See their current newsletter.

**Comment by DomainePlus** [comment] 2022-03-03 13:59
Thank you for keeping us informed!

**Comment by papakai** [comment] 2022-03-14 13:44
I got informed that OT&E and Live System/Production System are now reviewed and prepared/ready.
I am closing this issue therefore. Just in case there's still something not working as expected, just reopen and follow-up.

Enjoy your day!

**Closed by papakai** 2022-03-14 13:44 UTC
Labels: Backend System
